[package]
name = "vmw-logger"
version = "0.1.1"
edition = "2021"
description = "A VMWare logger using built-in backdoor."
readme = "README.md"
repository = "https://github.com/Azvanzed/vmw-logger"
license-file = "LICENSE"

[dependencies]
log = "0.4.22"
